dtb-$(CONFIG_ARCH_SDM450) += Qualcomm_Technologies,_Inc._SDM450_+_PMI632_SOC.dtb

dtb-$(CONFIG_ARCH_SDM632) += Qualcomm_Technologies,_Inc._SDM632_+_PMI632_SOC.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
